### ISSUE TITLE
Shortcuts don't seem to translate into emoji unicode properly. 

### ISSUE THREAD

**Issue by mibby** [Vap0r1ze/EmojiChat#2]
Compiled as of commit https://github.com/Vap0r1ze/EmojiChat/commit/7d9545bc7f5fde8bf77d8d788fa689eebbec54e2

Edit: This is actually caused because the emoji list.txt had renames. Might want to update the default config example in that case.

~~Shortcuts don't seem to translate into emoji unicode properly. e.g. using ``:)`` for a smiley emoji.~~

Using longhand names such as ``:flag_us:`` display fine.

![link](https://i.imgur.com/lQQT1wi.png)

```
shortcuts:
  slightly_smiling_face:
  - ':)'
  - '(:'
  - ':slightly_smiling:'
  - ':slight_smile:'
  wink:
  - ';)'
  - '(;'
  yum:
  - ':P'
  sunglasses:
  - '8)'
  - 'B)'
  neutral_face:
  - ':|'
  - '|:'
  confused:
  - ':\'
  sob:
  - ';('
  - ');'
  slightly_frowning_face:
  - ':('
  - '):'
  v:
  - ':peace:'
  - ':peace_hand:'
  crazy_face:
  - ':crazy:'
  face_with_raised_eyebrow:
  - ':hmm:'
  shushing_face:
  - ':shh:'
  1st_place_medal:
  - ':first:'
  - ':1st:'
  2nd_place_medal:
  - ':second:'
  - ':2nd:'
  3rd_place_medal:
  - ':third:'
  - ':3rd:'
  microphone:
  - ':mic:'
  musical_keyboard:
  - ':piano:'
  video_game:
  - ':controller:'
  dart:
  - ':target:'
  game_die:
  - ':dice:'
  - ':die:'
  heart:
  - '<3'
  broken_heart:
  - '</3'
  zero:
  - ':0:'
  one:
  - ':1:'
  two:
  - ':2:'
  three:
  - ':3:'
  four:
  - ':4:'
  five:
  - ':5:'
  six:
  - ':6:'
  seven:
  - ':7:'
  eight:
  - ':8:'
  nine:
  - ':9:'
  keycap_ten:
  - ':ten:'
  - ':10:'
  asterisk:
  - ':*:'
  unamused:
  - '-_-'
  open_mouth:
  - ':o'
  grin:
  - ':D'
  face_with_raised_eyebrow:
  - 'o_O'
  smiling_imp:
  - '>:]'
```
